//
//  Languages.swift
//  Tsuki
//
//  Created by Tudor Ifrim on 28.07.2021.
//

import SwiftUI

var languagesDict: [String: LocalizedStringKey] = [
    "en" : "English",
    "ja" : "Japanese",
    "pl" : "Polish",
    "sh" : "Serbo-Croatian",
    "nl" : "Dutch",
    "it" : "Italian",
    "ru" : "Russian",
    "de" : "German",
    "hu" : "Hungarian",
    "fr" : "French",
    "fi" : "Finnish",
    "vi" : "Vietnamese",
    "el" : "Greek",
    "bg" : "Bulgarian",
    "es" : "Spanish (Es)",
    "pt-br" : "Portugese (Br)",
    "pt" : "Portugese (Bt)",
    "sv" : "Swedish",
    "ar" : "Arabic",
    "da" : "Danish",
    "zh" : "Chinese",
    "bn" : "Bengali",
    "ro" : "Romanian",
    "cs" : "Czech",
    "mn" : "Mongolian",
    "tr" : "Turkish",
    "id" : "Indonesian",
    "ko" : "Korean",
    "es-la" : "Spanish (LATAM)",
    "fa" : "Persian",
    "ms" : "Malai",
    "th" : "Thai",
    "ca" : "Catalan",
    "tl" : "Filipino",
    "zh-hk" : "Chinese (Trad)",
    "uk" : "Ukranian",
    "my" : "Burmese",
    "lt" : "Lithuanian",
    "he" : "Hebrew",
    "hi" : "Hindi",
    "no" : "Norwegian"
]

var languagesEmojiDict: [String: String] = [
    "en" : "🇬🇧",
    "ja" : "🇯🇵",
    "pl" : "🇵🇱",
    "sh" : "🇷🇸/🇭🇷",
    "nl" : "🇳🇱",
    "it" : "🇮🇹",
    "ru" : "🇷🇺",
    "de" : "🇩🇪",
    "hu" : "🇭🇺",
    "fr" : "🇫🇷",
    "fi" : "🇫🇮",
    "vi" : "🇻🇳",
    "el" : "🇬🇷",
    "bg" : "🇧🇬",
    "es" : "🇪🇸",
    "pt-br" : "🇵🇹",
    "pt" : "🇵🇹",
    "sv" : "🇸🇪",
    "ar" : "🇸🇦",
    "da" : "🇩🇰",
    "zh" : "🇨🇳",
    "bn" : "🇮🇳",
    "ro" : "🇷🇴",
    "cs" : "🇨🇿",
    "mn" : "🇲🇳",
    "tr" : "🇹🇷",
    "id" : "🇮🇩",
    "ko" : "🇰🇷/🇰🇵",
    "es-la" : "🇪🇸",
    "fa" : "🇮🇷",
    "ms" : "🇮🇩",
    "th" : "🇹🇭",
    "ca" : "🇦🇩",
    "tl" : "🇵🇭",
    "zh-hk" : "🇨🇳",
    "uk" : "🇺🇦",
    "my" : "🇲🇲",
    "lt" : "🇱🇹",
    "he" : "🇮🇱",
    "hi" : "🇮🇳",
    "no" : "🇳🇴"
]
